version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: belong-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - belong-network

  # Optional: pgAdmin for database management (uncomment if needed)
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: belong-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@belong.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - belong-network

volumes:
  postgres_data:
    driver: local

networks:
  belong-network:
    driver: bridge
